Auto-splitting Updates
LiveSplit/livesplit-core pull request #477
Opened 2021-11-11 10:27 UTC by P1n3appl3

@TheTedder and I have done some major cleanup of the auto-splitting rework that was living on his branch for the past year or so. We want this to live on the upstream repo so that it's more visible and less likely to keep getting out of sync.

The major changes from the current `auto-splitting` branch are as follows:
- The function interface exposed to the wasm autosplitters has been completely redone, see the doc comment in `src/auto_splitting/mod.rs` for details
- The `process` module has been rewritten using some off the shelf crates that support reading process memory in a platform agnostic way.
- The WIP WASI support and associated tests have been removed. We plan to eventually use WASI but for now we just support `wasm32-unknown-unknown` auto-splitters

Since all of the functionality is behind the non-default `auto-splitting` feature merging it into master should probably be fine, but if y'all want to wait until it's "stabilized" then we can merge this into its own branch.

2021-11-11 12:04 UTC, CryZe requested changes

2021-11-11 12:04 UTC, CryZe commented on crates/livesplit-auto-splitting/Cargo.toml
> +anyhow = "1.0.45"
We likely want `snafu` instead. This was just a little more convenient for prototyping.

2021-11-11 12:04 UTC, CryZe commented on src/auto_splitting/mod.rs
> +/// inside the autosplitter, use `set_variable()`.
That's not what `set_variable` is for.

2021-11-11 12:04 UTC, CryZe commented on src/auto_splitting/mod.rs
> +        unsafe { std::mem::transmute(self.0.read().current_phase()) }
That's too unsafe for something that would be a trivial match.

2021-11-11 12:04 UTC, CryZe commented on src/auto_splitting/mod.rs
> +struct AST(SharedTimer);
Is this even true? Usually you can implement traits if at least part of the type (being the Timer) is defined in your own crate. I might be wrong though. But worth checking again.

2021-12-10 08:44 UTC, P1n3appl3 commented on crates/livesplit-auto-splitting/src/process.rs
> +    handle: ProcessHandle,
bugfix: rbspy/read-process-memory#16

2021-12-14 17:37 UTC, CryZe commented on crates/livesplit-auto-splitting/src/process.rs
> +        sysinfo.refresh_processes();
I just randomly stumbled upon this: https://blog.guillaume-gomez.fr/articles/2021-12-14+sysinfo%3A+version+0.22+and+FreeBSD+support

Apparently you can refresh just specific processes now.

2022-01-02 03:15 UTC, CryZe commented on crates/livesplit-auto-splitting/src/process.rs
> +        sysinfo.refresh_processes();
I implemented this in the dependency update commit I believe.

2022-01-02 03:32 UTC, CryZe commented
The crate probably needs `#![warn(missing_docs)]` and then all those warnings need to be resolved. I think that's mostly it.

2022-01-02 20:58 UTC, KaDiWa4 commented
wasmtime doesn't support 32-bit Windows, maybe there should be an extra condition in `.github/workflows/test.sh` to not enable `--all-features`

2022-01-04 00:35 UTC, CryZe commented
Process::is_open is absurdly slow. I don't think we can just "refresh all processes".
![https://i.imgur.com/e1LVnsI.png](https://i.imgur.com/e1LVnsI.png)

2022-01-08 04:14 UTC, CryZe approved these changes

2022-01-08 04:34 UTC, merged